name: flutter_template
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.0
  go_router: ^10.1.2
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.4.0
  lottie: ^2.6.0
  roggle: ^0.3.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.24.0+1


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
